#!/usr/bin/pytho
def raise_exception_msg(message=""):
    raise NameError(message)
